---
title: "Missing Data Handling"
output: html_notebook
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
```

```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(Hmisc))
suppressPackageStartupMessages(library(mice))
suppressPackageStartupMessages(library(missRanger))
suppressPackageStartupMessages(library(missForest))
suppressPackageStartupMessages(library(VIM))
```

```{r}
file_path <- "./data/crx.data"

# file was not previously downloaded
if (!file.exists(file_path)) {
  url <- "https://archive.ics.uci.edu/ml/machine-learning-databases/credit-screening/crx.data"
  dir.create(path = "./data")
  download.file(url = url, destfile = file_path)
}

# file was previously downloaded
credit_approval <- read.csv(file = file_path, header = F)
```

```{r}
colnames(credit_approval) <-c("Gender", "Age", "Debt", "Married", "BankCustomer", "EducationLevel", "Ethnicity", "YearsEmployed", "PriorDefault", "Employed", "CreditScore", "DriversLicense", "Citizen", "ZipCode", "Income", "Approved")
```

```{r}
credit_approval %>% summary()
```
# Filtering observations and setting to NA
```{r}
credit_approval$Gender[credit_approval$Gender == "?"] <- NA
credit_approval$Age[credit_approval$Age == "?"] <- NA
credit_approval$Married[credit_approval$Married == "?"] <- NA
credit_approval$BankCustomer[credit_approval$BankCustomer == "?"] <- NA
credit_approval$Ethnicity[credit_approval$Ethnicity == "?"] <- NA
credit_approval$ZipCode[credit_approval$ZipCode == "?"] <- NA
credit_approval$EducationLevel[credit_approval$EducationLevel == "?"] <- NA
credit_approval$PriorDefault[credit_approval$PriorDefault == "?"] <- NA
credit_approval$Employed[credit_approval$Employed == "?"] <- NA
credit_approval$DriversLicense[credit_approval$DriversLicense == "?"] <- NA
credit_approval$Citizen[credit_approval$Citizen == "?"] <- NA
credit_approval$Approved[credit_approval$Approved == "?"] <- NA
```

```{r}
credit_approval <- credit_approval %>%
  dplyr::mutate(Age = as.numeric(as.character(Age))) %>%
  dplyr::mutate(Gender = factor(Gender)) %>%
  dplyr::mutate(Married = factor(Married)) %>%
  dplyr::mutate(BankCustomer = factor(BankCustomer)) %>%
  dplyr::mutate(Ethnicity = factor(Ethnicity)) %>%
  dplyr::mutate(ZipCode = as.numeric(as.character(ZipCode))) %>%
  dplyr::mutate(EducationLevel = factor(EducationLevel)) %>%
  dplyr::mutate(PriorDefault = factor(PriorDefault)) %>%
  dplyr::mutate(Employed = factor(Employed)) %>%
  dplyr::mutate(DriversLicense = factor(DriversLicense)) %>%
  dplyr::mutate(Citizen = factor(Citizen)) %>%
  dplyr::mutate(Approved = factor(Approved))
```

#Missing Data Handling
#Mice
```{r}
md.pattern(credit_approval)
```
#VIM
```{r}
VIM::aggr(x = credit_approval, softVars = T)
```
## Removing Observations with NA
```{r}
credit_approval_removed_NAs <- credit_approval %>%
  na.omit()
```
## Univariate imputation
```{r}
credit_approval_impute <- credit_approval
credit_approval_impute$Age <- Hmisc::impute(x=credit_approval_impute$Age)
```

```{r}
set.seed(123)
missRanger::imputeUnivariate(c(NA, 0, 1, 0, 1))
```

```{r}
set.seed(125)
missRanger::imputeUnivariate(c(NA, 0, 1, 0, 1))
```
## Multivariate Imputation

## missRanger
```{r}
credit_approval_missRanger <- missRanger(data = credit_approval)
```

```{r}
summary(credit_approval_missRanger)
```
## missForest
```{r}
credit_approval_missForest <- missForest(credit_approval)$ximp
```

```{r}
summary(credit_approval_missForest)
```
## MICE
```{r}
mice_model <- mice(data = credit_approval, m = 5, method = 'pmm')
credit_approval_mice <- as_tibble(mice_model$data)
```
# Results Comparison
```{r}
credit_all_models <- rbind(
  credit_approval_removed_NAs %>% add_column(method = "Removed NA"),
  credit_approval_missForest %>% add_column(method = "missForest"),
  credit_approval_missRanger %>% add_column(method = "missRanger"),
  credit_approval_mice %>% add_column(method = "mice")
)
```

# Further data processing
```{r}
credit_all_models <- credit_all_models %>%
  dplyr::mutate(Gender = ifelse(Gender == "a", 1, 0)) %>%
  dplyr::mutate(Age = as.numeric(as.character(Age))) %>%
  dplyr::mutate(Approved = ifelse(Approved == "+", 1, 0)) %>%
  dplyr::select(Gender, Age, Debt, CreditScore, ZipCode, method)
credit_all_models_scaled <- credit_all_models[, 1:5] %>% scale() %>%
  as.tibble()
credit_all_models_scaled$method <- credit_all_models$method

credit_all_gather <- credit_all_models_scaled %>%
  gather(key = "variable", value = "value", 1:5) %>%
  mutate(value = as.numeric(value)) %>%
  mutate(varable = as.factor(variable)) %>%
  mutate(method = as.factor(method))
  
```

```{r}
g <- ggplot(credit_all_gather, aes(x = variable, y = value, col = method))
g <- g + geom_boxplot()
g <- g + labs(title = "Model Comparison", x = "Method", y = "Scaled Value [-]")
g
```

