---
title: "ROC Curve"
output: html_notebook
---



```{r}
library(tidyverse)
library(randomForest)
library(e1071)
library(pROC)
library(keras)

```
# Train / Validation/ Test Split
```{r}
train_ratio <- 0.6
validation_ratio <- 0.2
test_ratio <- 1 - train_ratio - validation_ratio
```
# Function for Train/ Validation / Test Split
```{r}
train_val_test_split <- function(df, train_ratio = 0.6, val_ratio = 0.2, test_ratio = 0.2) {
  n_obs <- nrow(df)
  sample_size_train <- floor(train_ratio * n_obs)
  sample_size_valid <- floor(validation_ratio * n_obs)
  sample_size_test <- floor(test_ratio * n_obs)

  indices_train <- base::sample(x = 1:n_obs, size = sample_size_train) %>% sort
  indicies_not_train <- base::setdiff(x = 1:n_obs, indices_train)
  indicies_validation <- base::sample(x = indicies_not_train, size = sample_size_valid)
  indicies_test <- base::setdiff(indicies_not_train, indicies_validation)

  train <- df[indices_train, ]
  val <- df[indicies_validation, ]
  test <- df[indicies_test, ]
  list(train, val, test)
  
}
```


# Data Import


```{r}
df <- read.csv("./data/adult.data")
column_names <- c("age", "workclass", "fnlwgt", "education", "education-num", "marital_status", "occupation", "relationship", "race", "sex", "capital_gain", "capital_loss", "hours_per_week", "native-country", "income")

colnames(df) <- column_names

df$'education-num' <- NULL
df$'native-country' <- NULL

# Video example gave error (thank you copilot for the coding help!!)
df$income <- as.factor(df$income)

```

## Train / Validation / Test Split
```{r}
set.seed(1000)
df <- df[sample(x = 1:nrow(df), size = 2000), ]

c(train, val, test) %<-% train_val_test_split(df = df, train_ratio = 0.8, val_ratio = 0.2, test_ratio = 0)
```

# Fitting the model

## Logistic Regression
```{r}
log_reg_fit <- glm(formula = income ~ .,
                   family = binomial,
                   data = train)
```
# Creating predictions
```{r}
predictions <- predict(object = log_reg_fit,
                       newdata = val,
                       type = "response")

val$income_pred_logreg_raw <- predictions
val$income_pred_logreg <- ifelse(predictions >.5, 1, 0)
```

## Random Forest
```{r}
rf_fit <- randomForest(income ~ ., data = train, probability = T)

rf_pred_class <- predict(object = rf_fit, newdata = val, type="class")
rf_pred <- predict(object = rf_fit, newdata = val, type="prob")
rf_pred_1 <- rf_pred[, 2]
```

# Support Vector Machines
```{r}
svm_fit <- svm(income ~ ., data = train, probability = T)

svm_pred <- predict(object = svm_fit, newdata = val, probability = F)
svm_pred_prob <- predict(object = svm_fit, newdata = val, probability = T)
svm_pred_prob_0 <- attr(svm_pred_prob, "probabilities")[, 1]
svm_pred_prob_1 <- attr(svm_pred_prob, "probabilities")[, 2]
```

# Model Evaluation

## Confusion Matrix

```{r}
val$group <- NA
threshold <- 0.6

val$group[val$income_pred_logreg_raw >= threshold & val$income == "1"] <- "TP"
val$group[val$income_pred_logreg_raw >= threshold & val$income == "0"] <- "FP"
val$group[val$income_pred_logreg_raw < threshold & val$income == "1"] <- "FN"
val$group[val$income_pred_logreg_raw < threshold & val$income == "0"] <- "TN"

g <- ggplot(val, aes(x = income,
                     y = income_pred_logreg_raw,
                     col = group))

g <- g + geom_jitter()
g <- g + geom_hline(yintercept = threshold)
g <- g + theme_bw()
g <- g + scale_color_discrete(name = "Group")
g <- g + xlab ("Actual")
g <- g + ylab ("Predicted")
g <- g + ggtitle ("Impact of Threshold on FN/FP/TN/TP")
g
```

```{r}
table(val$income, val$income_pred_logreg)
```
```{r}
mean(val$income == val$income_pred_logreg)
```


# ROC
```{r}
total <- nrow(val)
roc_df_rf <- data_frame(threshold = seq(0.01, 1, 0.001),
                        fp = NA,
                        tp = NA,
                        fn = NA,
                        tn = NA)

for (thres_pos in 1:nrow(roc_df_rf)) {
  thres <- roc_df_rf$threshold[thres_pos]
  roc_df_rf$tp[thres_pos] <- sum(as.numeric(rf_pred_1) >= thres & val$income == 1)
  roc_df_rf$fp[thres_pos] <- sum(as.numeric(rf_pred_1) >= thres & val$income == 0)
  roc_df_rf$fn[thres_pos] <- sum(as.numeric(rf_pred_1) < thres & val$income == 1)
  roc_df_rf$tn[thres_pos] <- sum(as.numeric(rf_pred_1) < thres & val$income == 0)
}

roc_df_rf$tpr <- roc_df_rf$tp / (roc_df_rf$fn + roc_df_rf$tp)
roc_df_rf$fpr <- roc_df_rf$fp / (roc_df_rf$tn + roc_df_rf$fp)
roc_df_rf$method <- "Random Forest"
```

```{r}
total <- nrow(val)
roc_df_svm <- data_frame(threshold = seq(0.01, 1, 0.001),
                        fp = NA,
                        tp = NA,
                        fn = NA,
                        tn = NA)

for (thres_pos in 1:nrow(roc_df_svm)) {
  thres <- roc_df_svm$threshold[thres_pos]
  roc_df_svm$tp[thres_pos] <- sum(as.numeric(svm_pred_prob_1) >= thres & val$income == 1)
  roc_df_svm$fp[thres_pos] <- sum(as.numeric(svm_pred_prob_1) >= thres & val$income == 0)
  roc_df_svm$fn[thres_pos] <- sum(as.numeric(svm_pred_prob_1) < thres & val$income == 1)
  roc_df_svm$tn[thres_pos] <- sum(as.numeric(svm_pred_prob_1) < thres & val$income == 0)
}

roc_df_svm$tpr <- roc_df_rf$tp / (roc_df_svm$fn + roc_df_svm$tp)
roc_df_svm$fpr <- roc_df_rf$fp / (roc_df_svm$tn + roc_df_svm$fp)
roc_df_svm$method <- "SVM"
```

```{r}
total <- nrow(val)
roc_df <- data_frame(threshold = seq(0.01, 1, 0.001),
                        fp = NA,
                        tp = NA,
                        fn = NA,
                        tn = NA)

for (thres_pos in 1:nrow(roc_df)) {
  thres <- roc_df$threshold[thres_pos]
  roc_df$tp[thres_pos] <- sum(val$income_pred_logreg_raw >= thres & val$income == 1)
  roc_df$fp[thres_pos] <- sum(val$income_pred_logreg_raw >= thres & val$income == 0)
  roc_df$fn[thres_pos] <- sum(val$income_pred_logreg_raw < thres & val$income == 1)
  roc_df$tn[thres_pos] <- sum(val$income_pred_logreg_raw < thres & val$income == 0)
}

roc_df$tpr <- roc_df$tp / (roc_df$fn + roc_df$tp)
roc_df$fpr <- roc_df$fp / (roc_df$tn + roc_df$fp)
roc_df_logreg <- roc_df
roc_df_logreg$method <- "LogReg"
```

```{r}
roc_df <- roc_df_logreg %>%
  rbind(., roc_df_svm) %>%
  rbind(., roc_df_rf)

g <- ggplot(roc_df, aes(x =fpr, y = tpr, col = method))
g <- g + geom_line()
g <- g + geom_abline(intercept = 0)
g <- g + coord_cartesian(xlim = c(0, 1), ylim = c(0, 1))
g <- g + theme_bw()
g <- g + scale_color_discrete(name = "Mrthod")
g <- g + xlab ("FPR [-]")
g <- g + ylab ("TPR [-]")
g <- g + ggtitle("ROC Curve")
g
```
## AUC
```{r}
# SVM
pROC::auc(as.numeric(val$income), as.numeric(svm_pred))

# Logistic Regression
pROC::auc(as.numeric(val$income), as.numeric(val$income_pred_logreg))

# Random Forest
pROC::auc(as.numeric(val$income), as.numeric(rf_pred_class))
```
# Cost Function

```{r}
cost <- function(predictions, actual, threshold, cost_of_fp, cost_of_fn){
  sum(predictions >= threshold & actual == 0) * cost_of_fp +
  sum(predictions < threshold & actual == 1) * cost_of_fn  
}
```

```{r}
fp_cost <- 10
fn_cost <- 1
total <- nrow(val)
roc_df <- data_frame(threshold = seq(0.01, 1, 0.001),
                     fp = NA,
                     tp = NA,
                     fn = NA,
                     tn = NA,
                     cost = NA)

for (thres_pos in 1:nrow(roc_df)) {
  thres <- roc_df$threshold[thres_pos]
  roc_df$tp[thres_pos] <- sum(val$income_pred_logreg_raw >= thres & val$income == 1)
  roc_df$fp[thres_pos] <- sum(val$income_pred_logreg_raw >= thres & val$income == 0)
  roc_df$fn[thres_pos] <- sum(val$income_pred_logreg_raw < thres & val$income == 1)
  roc_df$tn[thres_pos] <- sum(val$income_pred_logreg_raw < thres & val$income == 0)
  roc_df$cost[thres_pos] <- cost(predictions = val$income_pred_logreg_raw,
                                 threshold = thres,
                                 actual = val$income,
                                 cost_of_fp = fp_cost,
                                 cost_of_fn = fn_cost)
  
}

roc_df$tpr <- roc_df$tp / (roc_df$fn + roc_df$tp)
roc_df$fpr <- roc_df$fp / (roc_df$tn + roc_df$fp)
roc_df_logreg <- roc_df
roc_df_logreg$method <- "LogReg"
```

```{r}
g <- ggplot(roc_df, aes(x = fpr, y = tpr, col = cost))
g <- g + geom_line(linewidth = 2)
g <- g + geom_point(data = roc_df[which(min(roc_df$cost) == roc_df$cost), ] %>% head(1), col = "black", size = 2)
g <- g + geom_abline(intercept = 0)
g <- g + coord_cartesian(xlim = c(0, 1), ylim = c(0, 1))
g <- g + theme_bw()
g <- g + scale_color_gradientn(colours= rev(rainbow(5)), name = "Cost Value [-]")
g <- g + xlab ("FPR [-]")
g <- g + ylab ("TPR [-]")
g <- ggtitle("ROC Curve")
g
```



