---
title: "Week 7: Building a ML End-to-End Project"
output: html_notebook
---


# Import packages

```{r}
library(caret)
library(corrplot)
library(mlbench)

data(BostonHousing)

```

# Validation Dataset

```{r}

set.seed(7)

# Create a list of 80% of the rows in the original dataset we can use for training

validationIndex <- createDataPartition(BostonHousing$medv, p = .80, list = FALSE)

# Select 20% of the data for validation

validation <- BostonHousing[-validationIndex, ]

# Use the remaining 80% of data for training and testing the models

dataset <- BostonHousing[validationIndex, ]

```


# Analyse data

```{r}

# Dimensions of dataset

dim(dataset)

# list types for each attribute

sapply(dataset, class)

# Take a peek at the first 20 rows of the dataset

head(dataset, n=20)

# summarize attribute distributions

summary(dataset)

```


# Converting types and Coreelation

```{r}
# Uni lab had errors (corrected)

# convert chas to a numeric attribute

dataset$chas <- as.numeric(as.character(dataset$chas))

# correlation between all the numeric attributes

cor(dataset[, sapply(dataset, is.numeric)])

```


# Unimodal data visualizations

```{r}

# histograms each attribute

par(mfrow = c(2,7))

for (i in 1:13) {
  hist(dataset[, i], main = names(dataset)[i])
  
}

```

```{r}

# density plot for each attribute

par(mfrow = c(2,7))
for (i in 1:13) {
  plot(density(dataset[,i]), main = names(dataset)[i])
  
}

```

```{r}

# Boxplots for each attribute

par(mfrow = c(2,7))
for (i in 1:13) {
  boxplot(dataset[,i], main = names(dataset)[i])
  
}
```

```{r}

# scatterplot matrix

pairs(dataset[,1:13])

```

```{r}

# correlation plot

correlations <- cor(dataset[,1:13])

corrplot(correlations, method = "circle")

```

