---
title: "Week 6: Clustering"
output: html_notebook
---

# Load Libraries

```{r}

library(tidyverse)
library(corrplot)
library(gridExtra)
library(GGally)
library(knitr)

```


# Read the stats

```{r}

wines <- read.csv("Wine.csv")

```


# Remove the Type column

```{r}

wines <- wines[, -14] # Remove the 'labelled' column Customer_Segment

```

# Explore the data

```{r}
kable(head(wines))
```


# Data analysis

```{r}

# Histogram for each Attribute

wines %>%
  gather(Attributes, value, 1:13) %>%
  ggplot(aes(x = value, fill = Attributes)) +
  geom_histogram(colour = "black", show.legend = FALSE) +
  facet_wrap(~ Attributes, scales = "free_x") +
  labs(x = "Values", y = "Frequency",
       title = "Wines Attributes - Histograms") +
  theme_bw()

```

# Density plot for each attribute

```{r}

wines %>%
  gather(Attributes, value, 1:13) %>%
  ggplot(aes(x = value, fill = Attributes)) +
  geom_density(colour = "black", alpha =0.5, show.legend = FALSE) +
  facet_wrap(~ Attributes, scales = "free_x") +
  labs(x = "Values", y = "Density",
       title = "Wines Attributes - Density plots")+
  theme_bw()



```

# Boxplot For each Attribute

```{r}

wines %>%
  gather(Attributes, values, c(1:4, 6:12)) %>%
  ggplot(aes(x = reorder(Attributes, values, FUN = median), y = values, fill = Attributes)) +
  geom_boxplot(show.legend = FALSE) +
  labs(title = "Wines Attributes BOxplots") +
  theme_bw() +
  theme(axis.title.y = element_blank(),
        axis.title.x = element_blank()) +
  ylim(0, 35) +
  coord_flip()

```

# Correlation Matrix

```{r}

corrplot(cor(wines), type = "upper", method = "ellipse", tl.cex = 0.9)

```

# Relationship between Phenols and Flavanoids

```{r}

ggplot(wines, aes(x = Phenols, y = Flavanoids)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Wines Attributes",
       subtitle = "Relationship between Phenols and Flavanoids") +
  theme_bw()

```

# Data Preparation

```{r}

# Normalization

winesNorm <- as.data.frame(scale(wines))

# Original data

p1 <- ggplot(wines, aes(x = Alcohol, y = Malic.acid)) +
  geom_point()
labs(title = "Original data") +
  theme_bw()



# Normalized data

p2 <- ggplot(winesNorm, aes(x = Alcohol, y = Malic.acid)) +
  geom_point()
labs(title = "Normalized data") +
  theme_bw()

# Subplot

grid.arrange(p1, p2, ncol = 2)

```

# k-means execution

```{r}

#Execution of k-means with k=2

set.seed(1234)

wines_k2 <- kmeans(winesNorm, centers = 2)

# The kmeans() function returns an object of class "kmeans" with information about the partition:
# cluster - A vector of integers indicating the cluster to which each point is allocated.
# centers - A matrix of cluster centers.
# size - The number of points in each cluster.

# Cluster to which each point is allocated

wines_k2$cluster

# Cluster centers

wines_k2$centers

# Cluster size

wines_k2$size

# Between-cluster sum of squares

wines_k2$betweenss

# Within-cluster sum of squares

wines_k2$withinss

# Total within-cluster sum of squares

wines_k2$tot.withinss

# Total sum of squares

wines_k2$totss

```

# How many clusters?

```{r}

bss <- numeric()

wss <- numeric()

# Run the algorithm for different values of k

set.seed(1234)

for (i in 1:10) {
  # for each k, calculate betweenss and tot.withinss
  
  bss[i] <- kmeans(winesNorm, centers = i)$betweenss
  
  wss[i] <- kmeans(winesNorm, centers = i)$tot.withinss
}

# Between-cluster sum of squares vs Choice of k

p3 <- qplot(1:10, bss, geom = c("point", "line"),
            xlab = "Number of clusters",
            ylab = "Between-cluster sum of squares") +
  scale_x_continuous(breaks = seq(0, 10, 1)) +
  theme_bw()

# Total within-cluster sum of squares vs Choice of k

p4 <- qplot(1:10, wss, geom = c("point", "line"),
            xlab = "Number of clusters",
            ylab = "Total within-cluster sum of squares") +
  scale_x_continuous(breaks = seq(0, 10, 1)) +
  theme_bw()

# subplot

grid.arrange(p3, p4, ncol = 2)

```

# Results

```{r}

# Execution of k-means with k=3

set.seed(1234)

wines_k3 <- kmeans(winesNorm, centers = 3)

# Mean values of each cluster

aggregate(wines, by = list(wines_k3$cluster), mean)

# Clustering

ggpairs(cbind(wines, Cluster=as.factor(wines_k3$cluster)),
        columns = 1:6, aes(colour = Cluster, alpha = 0.5),
        lower = list(continuous="points"),
        upper = list(continuous="blank"),
        axisLabels = "none", switch = "both")+
  theme_bw()

```

